### ISSUE TITLE
Heartbeat loop disconnects the socket unexpectedly

### ISSUE THREAD

**Issue by wiredmb** [jasonrbriggs/stomp.py#219]
I'm using Stomp.py Version 4.1.15 and connecting the stomp consumer to Amazon MQ broker. I set heartbeat parameter to <0,30000>. Broker is sending heartbeat every 30 secs. Here is the scenario where consumer disconnects the connection:
1. Broker sends heartbeat at X.
2. Broker sends a message at X + 4. 
3. Heartbeat loop wakes up in the meantime, calculates difference between `received_heartbeat` and `now` which is 11 secs and sleeps for 34 secs (`receive_sleep` is 45 secs). 
4. Broker skips heartbeat at X + 30 (because of message sent in #2).
5. Heartbeat loop wakes up after 34 secs, calculates difference between `received_heartbeat` and `now` which is slightly greater than `receive_sleep` (in my case, 45.02 secs) and disconnects the connection with heartbeat timeout event. 
6. Also throws an exception:
```
on_heartbeat_timeout
Before Sleep: received_heartbeat: Fri Sep  7 16:43:41 2018, receive_sleep: 45.0, now: Fri Sep  7 16:44:27 2018
Exception in thread StompHeartbeatThread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/stomp/listener.py", line 266, in __heartbeat_loop
    sleep_time = min(next_events)
ValueError: min() arg is an empty sequence
```

The possible solution could be to add `grace time` while checking for `diff_receive > self.receive_sleep` in heartbeat loop. Please suggest.

**Comment by jasonrbriggs** [comment]
Believe this is resolved in the latest version.

**Comment by HWiese1980** [comment]
It is not. We're experiencing this issue right now. We're on `stomp.py v7.0.0`.

**Comment by HWiese1980** [comment]
Cause is that `next_events` is empty. It is empty because `self.next_outbound_heartbeat` is `None`. Furthermore, `self.received_heartbeat + self.receive_sleep - now` is ` <= 0.0` so that eventually there's nothing added to `next_events`. 

Source: `stomp/listener.py:271` and following lines

**Comment by HWiese1980** [comment]
@jasonrbriggs Have you seen this one? The error persists and it's a behavior I see quite often. 

I'll make a small change and send you a pull request for review that should fix this particular problem. I'm not sure if it has some implications or impacts downstream as I'm not that deep in your code yet.
